databases:
  - name: mrp-db
    plan: free

services:
  - type: web
    name: mrp-backend
    plan: free
    runtime: node
    rootDir: backend-nest
    buildCommand: npm install && npm run build
    startCommand: sh -c "npx prisma generate && npx prisma db push && npm run prisma:seed && npx ts-node --transpile-only -r tsconfig-paths/register src/main.ts"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mrp-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8080
      - key: CORS_ORIGIN
        fromService:
          name: mrp-frontend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      # Strongly recommended so Render doesn’t default to an old Node:
      - key: NODE_VERSION
        value: 20

  - type: web
    name: mrp-frontend
    plan: free
    runtime: node
    rootDir: frontend-next
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: mrp-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
